# Generated by Django 3.0.4 on 2020-04-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200426_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cartitem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
